name: spotify

version: 1.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
