name: spotify

version: 1.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  assets_audio_player: ^3.0.6
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/spotify.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
